"""empty message

Revision ID: 13ff2fbb87f8
Revises: None
Create Date: 2016-06-21 17:24:07.386784

"""

# revision identifiers, used by Alembic.
revision = '13ff2fbb87f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee')
    op.add_column('user', sa.Column('pwd', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['pwd'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'pwd')
    op.create_table('fee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fee', sa.INTEGER(), nullable=True),
    sa.Column('reg_no', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['reg_no'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
